/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-RENAME.h
 #	source generated by 4D Plugin Wizard
 #	Project : RENAME
 #	author : miyako
 #	2019/10/14
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_RENAME_H
#define PLUGIN_RENAME_H

#include "4DPluginAPI.h"

#include "C_LONGINT.h"
#include "C_TEXT.h"

#pragma mark -

void RENAME(PA_PluginParameters params);

#endif /* PLUGIN_RENAME_H */
