/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : RENAME
 #	author : miyako
 #	2017/08/28
 #
 # --------------------------------------------------------------------------------*/



// --- RENAME
void RENAME(sLONG_PTR *pResult, PackagePtr pParams);
